name: build-resume

on:
  push:
    branches: [main]
    paths:
      - "main.tex"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: install TeX Live full
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: build resume
        run: |
          latexmk -xelatex main.tex

      - name: push pdf to target repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/saurabh254/portfolio-html.git target
          mkdir -p target/public
          cp main.pdf target/public/saurabh_resume.pdf
          cd target
          git config user.name "saurabh254"
          git config user.email "sauravvishwakarma030@gmail.com"
          git add public/saurabh_resume.pdf
          git commit -m "update resume"
          git push
